apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-config
  namespace: execution-service
data:
  KAFKA_BROKERS: "kafka.kafka.svc.cluster.local:9092"
  SUBMISSION_TOPIC: "code-submissions"
  RESULT_TOPIC: "code-results"
