apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
  namespace: execution-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
    spec:
      containers:
      - name: execution-service
        image: execution-service:0.0.2
        envFrom:
        - configMapRef:
            name: execution-config
        # The following limits are mandatory for any malicious code requests
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: false
          readOnlyRootFilesystem: false
