apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: execution-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: execution-service
